accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = "accounts"

urlpatterns = [
    # /accounts/signup/
    path('signup/', views.signup, name='signup'),

    # /accounts/logout/
    path('logout/', LogoutView.as_view(), name='logout'),

    # /accounts/login/
    path('login/', LoginView.as_view(
        template_name='accounts/login.html',
        redirect_authenticated_user=True
    ), name='login'),

    # /accounts/reset/
    path('reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),

    # /accounts/reset/done/
    path('reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),

    # /accounts/reset/<uidb64>/<token>/
    path('reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),

    # /accounts/reset/complete/
    path('reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

settings/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

app_name = "settings"

urlpatterns = [
    # /settings/password/
    path('password/', PasswordChangeView.as_view(
        template_name='settings/password_change.html',
        success_url=reverse_lazy('settings:password_change_done')
    ), name='password_change'),

    # /settings/password/done/
    path('password/done/', PasswordChangeDoneView.as_view(
        template_name='settings/password_change_done.html'
    ), name='password_change_done'),
]

tutorial/urls.py
from django.urls import path
from  . import views

app_name = "tutorial"

urlpatterns = [
    # /
    path('', views.index, name='index'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # /admin/
    path('admin/', admin.site.urls),

    # /
    path('', include('tutorial.urls', namespace='tutorial')),

    # / accounts/
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # / settings/
    path('settings/', include('settings.urls', namespace='settings')),
]

accounts/models.py
from django.db import models

# Create your models here.

settings/models.py
from django.db import models

# Create your models here.

tutorial/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import login
from .forms import SignUpForm
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView
)


def signup(request):
    if request.user.is_authenticated:
        return redirect('tutorial:index')
    else:
        if request.method == "POST":
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect('tutorial:index')
        else:
            form = SignUpForm()

        context = {'form': form, 'title': 'Sign Up'}
        return render(request, 'accounts/signup.html', context=context)


class CustomPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tutorial:index')
        else:
            return super().dispatch(*args, **kwargs)


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tutorial:index')
        else:
            return super().dispatch(*args, **kwargs)


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tutorial:index')
        else:
            return super().dispatch(*args, **kwargs)

settings/views.py
from django.shortcuts import render

# Create your views here.

tutorial/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'tutorial/index.html', {'title': "Home"})

templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
{% endblock stylesheet %}

{% block body %}

    <div class="container">

        <h1 class="text-center logo my-4">
            <a href="{% url 'tutorial:index' %}">Django Tutorial</a>
        </h1>

        <div class="row justify-content-center">

            <div class="col-lg-4 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                            <h3 class="card-title" style="text-align: center;">Log In</h3>

                            <form method="post" novalidate>

                                {% csrf_token %}

                                {% include 'includes/form.html' %}

                                <button type="submit" class="btn btn-lg btn-primary btn-block">Log In</button>

                            </form>
                    </div>

                    <div class="card-footer text-muted text-center">
                        New to Django Tutorial? <a href="{% url 'accounts:signup' %}">Sign up</a>
                    </div>

                </div>

                <div class="text-center py-2">

                  <small>
                    <a href="{% url 'accounts:password_reset' %}" class="text-muted">Forgot your password?</a>
                  </small>

                </div>

            </div>

        </div>

    </div>>

{% endblock body %}

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-6 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                            <h3 class="card-title" style="text-align: center;">Reset your password</h3>

                            <p>Enter your email address and we will send you a link to reset your password.</p>

                            <form method="post" novalidate>

                                {% csrf_token %}

                                {% include 'includes/form.html' %}

                                <button type="submit" class="btn btn-lg btn-primary btn-block">Send password reset email</button>

                            </form>
                    </div>

                </div>

            </div>

        </div>

    </div>>

{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-6 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                            <h3 class="card-title" style="text-align: center;">Password changed!</h3>

                            <div class="alert alert-success" role="alert">

                                You have successfully changed your password! You may now proceed to log in.

                            </div>

                             <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>

                    </div>

                </div>

            </div>

        </div>

    </div>>

{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-6 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                        {% if validlink %}

                            <h3 class="card-title" style="text-align: center;">Reset your password</h3>

                            <form method="post" novalidate>

                                {% csrf_token %}

                                {% include 'includes/form.html' %}

                                <button type="submit" class="btn btn-lg btn-success btn-block">Change password</button>

                            </form>

                        {% else %}

                            <h3 class="card-title">Reset your password</h3>

                            <div class="alert alert-danger" role="alert">

                              It looks like you clicked on an invalid password reset link. Please try again.

                            </div>

                            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">
                                Request a new password reset link
                            </a>

                        {% endif %}

                    </div>

                </div>

            </div>

        </div>

    </div>>

{% endblock content %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-6 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                            <h3 class="card-title" style="text-align: center;">Reset your password</h3>

                            <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>

                             <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>

                    </div>

                </div>

            </div>

        </div>

    </div>>

{% endblock content %}

templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Tutorial username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,
The Django Tutorial Team

templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
{% endblock stylesheet %}

{% block body %}

    <div class="container">

        <h1 class="text-center logo my-4">
            <a href="{% url 'tutorial:index' %}">Django Tutorial</a>
        </h1>

        <div class="row justify-content-center">

            <div class="col-lg-6 col-md-6 col-sm-8">

                <div class="card">

                    <div class="card-body">

                            <h3 class="card-title" style="text-align: center;">Please Sign Up</h3>

                            <form method="post" novalidate>

                                {% csrf_token %}

                                {% include 'includes/form.html' %}

                                <button type="submit" class="btn btn-lg btn-primary btn-block">Create an account</button>

                            </form>
                    </div>

                <div class="card-footer text-muted text-center">
                    Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
                </div>

            </div>

        </div>
    </div>

    </div>>

{% endblock body %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Corben&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />

    {% block stylesheet %}
    {% endblock stylesheet %}

    {% if title %}
      <title>{{title}} - Django Tutorial</title>
    {% else %}
      <title>Django Tutorial</title>
    {% endif %}

  </head>
  <body>

    {% block body %}

        <div class="container">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

      <a class="navbar-brand" href="{% url 'tutorial:index' %}">Django Tutorial</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">

        {% if user.is_authenticated %}

          <ul class="navbar-nav ml-auto">

              <li class="nav-item">
                 <a href="{% url 'settings:password_change' %}" class="nav-link my-2 my-sm-0">Change Password</a>
              </li>

              <li class="nav-item">
                  <a href="{% url 'accounts:logout' %}" class="nav-link ml-2 my-sm-0">Sign Out</a>
              </li>

          </ul>

      {% else %}

          <form class="form-inline ml-auto">

              <a href="{% url 'accounts:login' %}" class="btn btn-success my-2 my-sm-0">Log In</a>
              <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2 my-sm-0">Sign Up</a>

          </form>

      {% endif %}

      </div>

    </nav>

        {% block content %}
        {% endblock content %}

    </div>

    {% endblock body %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}

  <div class="alert alert-danger" role="alert">

    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}

  </div>

{% endif %}

{% for field in form %}

    <div class="form-group">

        {{ field.label_tag }}

        {% render_field field class=field|input_class %}

        {% for error in field.errors %}
            <div class="invalid-feedback">
                {{error}}
            </div>
        {% endfor %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
        {% endif %}

    </div>

{% endfor %}

templates/settings/password_change.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">

        <div class="col-lg-6 col-md-8 col-sm-10">

            <form method="post" novalidate>

                {% csrf_token %}

                {% include 'includes/form.html' %}

                <button type="submit" class="btn btn-success">Change password</button>
            </form>

        </div>

    </div>

{% endblock content %}

templates/settings/password_change_done.html
{% extends 'base.html' %}

{% block content %}

  <div class="alert alert-success" role="alert">

      <strong>Success!</strong> Your password has been changed!

  </div>

    <a href="{% url 'tutorial:index' %}" class="btn btn-secondary">Return to home page</a>

{% endblock %}

templates/tutorial/index.html
{% extends 'base.html' %}

{% block content %}
    Hello,
    <strong>
        {% if user.is_authenticated %}
            {{ user.username }}
        {% else %}
            Muchacho
        {% endif %}
    </strong>!
    <hr>
    <p>Welcome to the Django Authentication Tutorial!</p>
{% endblock content %}